from pathlib import Path
import os
import environ
import cloudinary
import cloudinary.uploader
import cloudinary.api
import logging

# ======================\n# LOGGING\n# ======================\nlogger = logging.getLogger(__name__)\n
# ======================\n# BASE & ENV\n# ======================\nBASE_DIR = Path(__file__).resolve().parent.parent\nenv = environ.Env()\nenviron.Env.read_env(os.path.join(BASE_DIR, ".env"))\nDEBUG = env.bool("DEBUG", default=False)\n# FIXED: Removed print statement, use logging instead\nlogger.info(f"Django DEBUG mode: {DEBUG}")\nSITE_ID = int(os.getenv("SITE_ID", 1))\n
# ======================\n# EMAIL (via Gmail SMTP)\n# ======================\nEMAIL_BACKEND = env("EMAIL_BACKEND")\nEMAIL_HOST = env("EMAIL_HOST")\nEMAIL_PORT = env.int("EMAIL_PORT")\nEMAIL_USE_TLS = env.bool("EMAIL_USE_TLS")\nEMAIL_HOST_USER = env("EMAIL_HOST_USER")\nEMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD")\nDEFAULT_FROM_EMAIL = EMAIL_HOST_USER\n
# ======================\n# CLOUDINARY\n# ======================\ncloudinary.config(\n    cloud_name=env("CLOUD_NAME"),\n    api_key=env("CLOUD_API_KEY"),\n    api_secret=env("CLOUD_API_SECRET"),\n    secure=True\n)\nDEFAULT_FILE_STORAGE = "cloudinary_storage.storage.MediaCloudinaryStorage"\n
# ======================\n# SECURITY\n# ======================\n# FIXED: Raise error if SECRET_KEY not provided\nSECRET_KEY = os.getenv("SECRET_KEY")\nif not SECRET_KEY:\n    if DEBUG:\n        # FIXED: Generate a temporary key for development\n        import secrets\n        SECRET_KEY = secrets.token_urlsafe(50)\n        logger.warning("⚠️ No SECRET_KEY provided. Using temporary development key.")\n    else:\n        raise ValueError(\n            "SECRET_KEY environment variable must be set in production. "+\n            "Generate one with: python -c 'from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())'"\n        )\nALLOWED_HOSTS = [\n    "fullstack-django-project-production.up.railway.app",\n    "localhost",\n    "127.0.0.1",\n]\nCSRF_TRUSTED_ORIGINS = [\n    "http://localhost",\n    "http://127.0.0.1",\n    "https://fullstack-django-project-production.up.railway.app",\n]\n# FIXED: Additional security settings\nCSRF_COOKIE_SECURE = not DEBUG  # HTTPS only in production\nSESSION_COOKIE_SECURE = not DEBUG\nSECURE_SSL_REDIRECT = not DEBUG\n
# ======================\n# APPLICATIONS\n# ======================\nINSTALLED_APPS = [\n    "django.contrib.admin",\n    "django.contrib.auth",\n    "django.contrib.contenttypes",\n    "django.contrib.sessions",\n    "django.contrib.messages",\n    "django.contrib.staticfiles",\n    "crm",\n    "django.contrib.sites",\n    # Allauth\n    "allauth",\n    "allauth.account",\n    "allauth.socialaccount",\n    # Cloudinary\n    "cloudinary_storage",\n    "cloudinary",\n    # Apps\n    "stellaric",\n    "users",\n    "cart",\n]\nSITE_ID = 1\nACCOUNT_FORMS = {\n    "login": "allauth.account.forms.LoginForm",\n    "signup": "users.forms.CustomSignupForm",\n}\n
# ======================\n# MIDDLEWARE\n# ======================\nMIDDLEWARE = [\n    "django.middleware.security.SecurityMiddleware",\n    "whitenoise.middleware.WhiteNoiseMiddleware",\n    "django.contrib.sessions.middleware.SessionMiddleware",\n    "django.middleware.common.CommonMiddleware",\n    "django.middleware.csrf.CsrfViewMiddleware",\n    "django.contrib.auth.middleware.AuthenticationMiddleware",\n    "django.contrib.messages.middleware.MessageMiddleware",\n    "django.middleware.clickjacking.XFrameOptionsMiddleware",\n    "allauth.account.middleware.AccountMiddleware",\n]\n
# ======================\n# URLS / WSGI\n# ======================\nROOT_URLCONF = "djangoProject.urls"\nWSGI_APPLICATION = "djangoProject.wsgi.application"\n
# ======================\n# TEMPLATES\n# ======================\nTEMPLATES = [\n    {\n        "BACKEND": "django.template.backends.django.DjangoTemplates",\n        "DIRS": [BASE_DIR / "templates"],\n        "APP_DIRS": True,\n        "OPTIONS": {\n            "context_processors": [\n                "django.template.context_processors.request",\n                "django.contrib.auth.context_processors.auth",\n                "django.contrib.messages.context_processors.messages",\n            ],\n        },\n    },\n]\n
# ======================\n# AUTHENTICATION\n# ======================\nAUTHENTICATION_BACKENDS = [\n    "django.contrib.auth.backends.ModelBackend",\n    "allauth.account.auth_backends.AuthenticationBackend",\n]\nACCOUNT_AUTHENTICATION_METHOD = "username_email"\nACCOUNT_EMAIL_REQUIRED = True\nACCOUNT_EMAIL_VERIFICATION = "mandatory"\nACCOUNT_CONFIRM_EMAIL_ON_GET = True\nACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 3\nACCOUNT_PREVENT_NUMERATION = False\nLOGIN_REDIRECT_URL = "/"\nACCOUNT_USERNAME_REQUIRED = True\nACCOUNT_SIGNUP_EMAIL_ENTER_TWICE = False\nACCOUNT_SESSION_REMEMBER = True\nLOGIN_URL = "account_login"\nLOGIN_REDIRECT_URL = "/"\nACCOUNT_LOGOUT_REDIRECT_URL = "/"\n
# ======================\n# DATABASE\n# ======================\nDATABASES = {\n    "default": {\n        "ENGINE": "django.db.backends.sqlite3",\n        "NAME": BASE_DIR / "db.sqlite3",\n    }\n}\n
# ======================\n# PASSWORD VALIDATION\n# ======================\nAUTH_PASSWORD_VALIDATORS = [\n    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},\n    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},\n    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},\n    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},\n]\n
# ======================\n# INTERNATIONALIZATION\n# ======================\nLANGUAGE_CODE = "en-us"\nTIME_ZONE = "UTC"\nUSE_I18N = True\nUSE_TZ = True\n
# ======================\n# STATIC FILES\n# ======================\nSTATIC_URL = "/static/"\nSTATIC_ROOT = BASE_DIR / "staticfiles"\nSTATICFILES_DIRS = [\n    BASE_DIR / "assets",\n]\nSTATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"\n
# ======================\n# MEDIA\n# ======================\nMEDIA_URL = "/media/"\nMEDIA_ROOT = BASE_DIR / "media"\nDEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"